#数据库
spring: 
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    druid:
      db1:
        url: jdbc:mysql://47.103.63.152:3306/lsdb_18?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
        username: redinfo
        password: 4008808919
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 10
        minIdle: 10
        maxActive: 20
      db2:
        url: jdbc:mysql://192.168.100.14:3306/jjyl_ls?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
        username: redinfo
        password: 4008808919
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 10
        minIdle: 10
        maxActive: 20

logging: 
  config: classpath:log4j2.xml

mybatis-plus: 
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  typeAliasesPackage: cn.redinfo.**.oo.**
  global-config: 
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #驼峰下划线转换
      column-underline: true
      db-type: mysql
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl